// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsct4R9n3hWGhM2vdJnp6PYPLDYX3JpoE',
    appId: '1:907509495254:web:c142d47d04c1d27f80e077',
    messagingSenderId: '907509495254',
    projectId: 'safehood-dce5e',
    authDomain: 'safehood-dce5e.firebaseapp.com',
    storageBucket: 'safehood-dce5e.firebasestorage.app',
    measurementId: 'G-9M521B7W0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFYbJxDeoRh-XP5ySaEHRufc_UdnmfKb4',
    appId: '1:907509495254:android:d478f7c1f506138c80e077',
    messagingSenderId: '907509495254',
    projectId: 'safehood-dce5e',
    storageBucket: 'safehood-dce5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsPKwUsMEkCUOj_QrMaFVqRrVDsamdegY',
    appId: '1:907509495254:ios:cb684a41a67507b480e077',
    messagingSenderId: '907509495254',
    projectId: 'safehood-dce5e',
    storageBucket: 'safehood-dce5e.firebasestorage.app',
    iosBundleId: 'com.example.safehome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsPKwUsMEkCUOj_QrMaFVqRrVDsamdegY',
    appId: '1:907509495254:ios:cb684a41a67507b480e077',
    messagingSenderId: '907509495254',
    projectId: 'safehood-dce5e',
    storageBucket: 'safehood-dce5e.firebasestorage.app',
    iosBundleId: 'com.example.safehome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsct4R9n3hWGhM2vdJnp6PYPLDYX3JpoE',
    appId: '1:907509495254:web:437a5ae8b832c01b80e077',
    messagingSenderId: '907509495254',
    projectId: 'safehood-dce5e',
    authDomain: 'safehood-dce5e.firebaseapp.com',
    storageBucket: 'safehood-dce5e.firebasestorage.app',
    measurementId: 'G-S18XFFEH8F',
  );
}
